export { default as Landing } from "./pages/Landing";
export { default as Auth } from "./pages/Auth";
export { default as Layout } from "./layout/Layout";
export { default as Community } from "./pages/Community";
export { default as Profile } from "./pages/Profile";
export { default as AdminHome } from "./pages/admin/Home";
export { default as AdminBlog } from "./pages/admin/Blog";
export { default as AdminBlogs } from "./pages/admin/AllBlogs";
export { default as AdminSelfAffirmation } from "./pages/admin/SelfAffirmation";
export { default as AdminMentalHealthTips } from "./pages/admin/MentalHealthTips";
export { default as FeedbackandReviews } from "./pages/admin/FeedbackandReviews";
export { default as BasicHome } from "./pages/basic/Home";
export { default as BasicBlogs } from "./pages/basic/AllBlogs";
export { default as BasicBlog } from "./pages/basic/Blog";
export { default as BasicSelfAffirmation } from "./pages/basic/SelfAffirmation";
export { default as BasicMentalHealthTips } from "./pages/basic/MentalHealthTips";
export { default as Logout } from "./pages/Logout";

export { default as NoPage } from "./pages/NoPage";
